server:
  port: 20003

spring:
  application:
    name: config-server
#  ## rabbitMQ用于Bus推送
  rabbitmq:
    host: 192.168.31.38
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        # 属性重载
        overrides:
          test: mytest
        git:
          uri: https://github.com/mtianyan/shop-cloud-config.git
          force-pull: true
          # 将配置文件放到接入方服务名称对应文件夹下面
          search-paths: '{application}'
          # username:
          # password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.38:20000/eureka/
  instance:
    instance-id: ${eureka.instance.ip-address}:${server.port}
    ip-address: 192.168.31.38
    prefer-ip-address: true
## 开启所有actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false